### ISSUE TITLE
Missing guest book entry 

### ISSUE THREAD

**Issue by muan** [jlord/the-muan-room#1]
@dreww hasn't signed it.

cc @jlord, also you're not watching this repo how come.

**Comment by jlord** [comment]
> also you're not watching this repo how come

WHY DOESN'T GITHUB ADD THIS FEATURE ALREADY!

Guess I need to finish this!

**Comment by muan** [comment]
You are still not watching it.

**Comment by jlord** [comment]
whooooooooooppsssss
